import "./globals.css";
import RootLayout from "./RootLayout";
// import { Providers } from "./provider";
// import {NextUIProvider} from '@nextui-org/react'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout(props) {
  const { children } = props;
  return (
    <html lang="en">
      <body>
        <RootLayout className="light"  >{children}</RootLayout>
      </body>
    </html>
  );
}

